### ISSUE TITLE
Async operations in mocha

### ISSUE THREAD

**Issue by erikmueller** [paypal/nemo-example-app#10]
I'm using nemo with mocha and it works pretty good so far. I was just wondering on what's the best approach to write a test. So here's what I think I understood so far (please correct if I'm wrong):

1. All actions (e.g. `nemo.view.someView().click()`) return a promise
2. Nevertheless all actions run synchronously and only the last must keep the test waiting

If both points are `true` then returning the last 'action' (which should be a promise) should do the trick and tell mocha it's an async test (see http://mochajs.org/#asynchronous-code last section).

Now my question is: Does this suffice or should you do sth like:

```js
return nemo.driver.get(url)
    .then(() => nemo.view.inputElement().click())
    .then(() => nemo.view.nextInputElement().click())
```

which explicitly makes sure all promises are run in order.

Cheers and thanks for sharing Nemo

**Comment by OuranosSkia** [comment]
In my approach I have found that as long as all actions are Selenium or Nemo based actions, you don't need to nest things in a "then" call. The purpose for doing such nesting comes out when you need the result of that call (eg, present check, find list of elements, getting text, etc...). To keep code cleaner, only doing thens for those such things and for when your test is done (so you can call success or error done call) makes your code easier to read and maintain.

As a side note to this, you can create your own functionality which follows this too by making sure you are using the promises implemented by selenium (see http://selenium.googlecode.com/git/docs/api/javascript/namespace_webdriver_promise.html)

**Comment by grawk** [comment]
Hi @erikmueller. Thanks for taking the time to share your thoughts.

Just to add to what @OuranosSkia said:

Selenium uses the `ControlFlow` class to queue up all commands which return its `Promise` class. It does this in a single turn of the event loop. The ControlFlow class will dynamically construct the promise chain around those commands and call the actual commands in order as previous commands resolve.

So, as long as you envision this while you're writing code, you can pretty easily (with practice) see when to add return statements, and when to interrupt the "synchronous" syntax with `then`.

I'd like to publish a blog post and/or a screencast to illuminate this a bit more. Because it's regularly misunderstood and also very powerful when used correctly.

In the meantime, you can look at the suite included in this repo to get a sense of "best practices". The suite is meant to illustrate how you go from your first iteration of writing a test, to the second, and then to the final factoring for reusability and maintainability.

## Generic spec
https://github.com/paypal/nemo-example-app/blob/master/test/functional/spec/generic-spec.js

Uses generic `nemo.view` methods and has locators defined inline. Notice use of "synchronous" syntax until we get [here](https://github.com/paypal/nemo-example-app/blob/master/test/functional/spec/generic-spec.js#L23). We use the resolved promise on this line to select and click the appropriate option.

## View spec
https://github.com/paypal/nemo-example-app/blob/master/test/functional/spec/view-spec.js

Uses the locator files to create dynamic functions. Now we've got the locators in a shared location. Note we are able to use synchronous syntax for every command [except the last one](https://github.com/paypal/nemo-example-app/blob/master/test/functional/spec/view-spec.js#L51-L55), where we want to resolve the promise chain and call either `done()` or `done(err)`

Still, this factoring of the code is unsatisfying because someone could later come along and say "I need this login functionality" and copy/paste the webdriver commands from this spec to another. Now we've got a maintenance problem.

## Flow spec
https://github.com/paypal/nemo-example-app/blob/master/test/functional/spec/flow-spec.js

Finally, the actual webdriver commands are abstracted to shareable classes. It would be much less troublesome if someone copy/pasted from this file to another, since any changes to the application structure will only require changes in one place (the flow classes) as opposed to the multiple places that may be using them.

Notice how we use `return` statements in the flow classes to ensure that the `ControlFlow` class can properly queue up the commands and we don't lose any errors. [Here](https://github.com/paypal/nemo-example-app/blob/master/test/functional/flow/navigate.js#L11) and [here](https://github.com/paypal/nemo-example-app/blob/master/test/functional/flow/navigate.js#L15) for example.

**Comment by erikmueller** [comment]
Thanks alot for sharing.
Think I will go with the approach described in the mentioned suite except for the use of the `done()` callback since mocha offers returning promises and thus marking the test as async.

Thanks again and I'm really looking forward to the blog post :+1:

**Comment by grawk** [comment]
I wasn't aware of that mocha feature until you mentioned it. I will assess whether the examples would benefit from that. Thanks.
