### ISSUE TITLE
Issues with grunt auto

### ISSUE THREAD

**Issue by NaveenNagendran** [paypal/nemo-example-app#11]
Machine : Windows 7

grunt auto throws following error :

1) @flow@ should execute high level functionality using flow modules:
Uncaught Error: Failure message did not appear
==== async task ====
Failure message did not appear
at Navigate.loginFailure (testNemo\test\functional\flow\navigate.js:18:31)
at Context. (testNemo\test\functional\spec\flow-spec.js:25:14)

2) @view@ should execute high level functionality using view methods:
Uncaught Error: [drivex.waitForElementVisible] Element not visible
==== async task ====

![grunt auto](https://cloud.githubusercontent.com/assets/13139974/8464374/7ea5b8c6-1ff6-11e5-871d-1c63c8bd75d9.JPG)

**Comment by grawk** [comment]
Hi @NaveenNagendran. You might have got this error with the PayPal internal version of the example application. Please can you refile this issue there? Reach out to me if you're not sure of the URL

**Comment by alallier** [comment]
I am trying to run the nemo example and am getting similar errors. When I type grunt automation I get this following output

```
  @flow@
    1) should execute high level functionality using flow modules
  2 failing
[grunt-loop-mocha] Total Runtime 3s
Warning: [grunt-loop-mocha] error, please check erroneous iteration(s): {"1439381569742-default":2} Use --force to continue.

Aborted due to warnings.

```

**Comment by grawk** [comment]
Re-opening

**Comment by grawk** [comment]
Hi @alallier can you try running the nemo mocha suite directly as follows:

```bash
$ nemoBaseDir=/Users/medelman/src/n/o/nemo-example-app/test/functional mocha --timeout 60s --grep @flow@ test/functional/spec/*.js
```

Note I am setting the env variable `nemoBaseDir` in the command. You will need to set it appropriately such that nemo gets configured properly.

Hopefully by running mocha directly you can see whatever exception the grunt task seems to be swallowing.

**Comment by alallier** [comment]
When I run this command replacing your username with my username I get mocha `mocha: command not found`

**Comment by alallier** [comment]
Update: Somehow didn't have Mocha installed, after installing I get

```
@flow@
    1) "before all" hook
    2) "after all" hook


  0 passing (44ms)
  2 failing

  1) @flow@ "before all" hook:
     nemoBadDriverProps: Nemo essential driver properties not found in configuration
  

  2) @flow@ "after all" hook:
     TypeError: Cannot call method 'quit' of undefined
      at Context.<anonymous> (test/functional/spec/flow-spec.js:22:17)

```

**Comment by grawk** [comment]
Sorry. I was neglecting to consider that I have mocha installed globally. you can reference the locally installed mocha instead as:
`node_modules/.bin/mocha` instead of `mocha`

@alallier it looks like perhaps you didn't set nemoBaseDir before running the command. Can you let me know what command you're using to run mocha and (if the command itself does not set it) what nemoBaseDir is set as.

**Comment by alallier** [comment]
I installed Mocha globally, when I ran the command you provided me above I got the following output

```
nemoBaseDir=/Users/alallier/src/n/o/nemo-example-app/test/functional mocha --timeout 60s --grep @flow@ test/functional/spec/*.js


  @flow@
    1) "before all" hook
    2) "after all" hook


  0 passing (42ms)
  2 failing

  1) @flow@ "before all" hook:
     nemoBadDriverProps: Nemo essential driver properties not found in configuration
  

  2) @flow@ "after all" hook:
     TypeError: Cannot call method 'quit' of undefined
      at Context.<anonymous> (test/functional/spec/flow-spec.js:22:17)
```

Which seems like a driver issue, although according to your documentation you don't have to a driver for Firefox? I was originally testing in Windows 10 but I moved over to Ubuntu 14.04 to test that way I could line up with your provided command.

**Comment by grawk** [comment]
I apologize I haven't had any time to try and understand what specifically might be happening on Ubuntu. If you get a chance, you can get more information by adding DEBUG=nemo* to your environment. That might give a better idea of what is missing from the configuration.

**Comment by alallier** [comment]
So what I did here was, a vanilla Ubuntu install, installed Mocha globally, and then followed the steps for sample app provided, which resulted in the errors I posted above.

**Comment by grawk** [comment]
Hi @alallier. Just wanted to let you know I'm still listening. But I've been consumed by a live support issue for almost two weeks now. Please hang in a little longer. I'm sincerely looking forward to getting back to this issue

**Comment by alallier** [comment]
Totally understand, will love your help at your convenience.

**Comment by grawk** [comment]
Sorry I'm just getting back to this. Way late. Really sorry. Anyway, I installed Ubuntu 14.0.3, which has Firefox 39 installed. Because the current "stable" release of nemo (v1.0.x) is using selenium-webdriver@2.44, it is unable to automate the default version of Firefox on this installation. I had to install the 1.1.0-alpha version of nemo which uses selenium-webdriver@2.46.1, in order to automate this version of Firefox.

I strongly suspect this is the issue you ran into as well @alallier.

If you're still working with nemo, please try cloning this branch instead:
`nemo-1.1-alpha`

nemo 1.1 will move out of alpha soon and the newer webdriver will be in the stable 1.1 release. In the meantime, there's no reason you can't use the alpha versions. Please see here for more information on the alpha:
https://github.com/paypal/nemo-docs/blob/master/upgrade-to-1.1.md
